### ISSUE TITLE
Provide prebuilt mod ;(

### ISSUE THREAD

**Issue by colt05** [Vexatos/CheatyComputers#1]
I want to test this mod for no reason :P

**Comment by Vexatos** [comment]
I... I am still not sure. This mod goes completely against the style of OpenComputers and was meant merely as a ridiculous joke...

**Comment by colt05** [comment]
true.. But I don't currently have Forge SRC/Eclipse on any of my computers XP

**Comment by gdude2002** [comment]
@colt05 Just use the gradlew.bat

**Comment by colt05** [comment]
0.o gradlew build can build without JDK or Forge SRC?

**Comment by gdude2002** [comment]
@colt05 you just need a JDK, gradle will download all the dependencies

**Comment by colt05** [comment]
oh

**Comment by colt05** [comment]
yeah but then there's the problem that every time i try to git clone and build something myself, there's always 1000s and 1000s of errors.

**Comment by gdude2002** [comment]
@colt05 [Here you go](https://bamboo.gserv.me/browse/MISC-CHEATC). JAR should be under "Artifacts" on the latest build.

**Comment by colt05** [comment]
Yay thanks!!! :D

**Comment by Vexatos** [comment]
I'll think about it, I guess...

**Comment by colt05** [comment]
@Vexatos you don't have to anymore, just provide @gdude2002 's link if they're ok with it

**Comment by Vexatos** [comment]
@colt05 The question is if I am okay with it.

**Comment by colt05** [comment]
that too

**Comment by gdude2002** [comment]
@Vexatos Let me know if you want me to disable the plan

EDIT: Done.

---

```
[14:14:28] <+Vexatos> my problem is if I want to build this mod
[14:14:29] <+Vexatos> I hate it
[14:14:34] <+Vexatos> it should not be used
[14:17:25] <+Vexatos> g: Please disable it for now
[14:17:28] <+Vexatos> I haven't decided yet
```
